# HomeWizard Battery Dynamic Control Automation (Simple Version)
# Author: Joost Smits
# Version: 0.8, 29 November 2025
# License: MIT
# Repository: https://github.com/eurojojo/homewizard-dynamic-battery
#
# This automation controls the HomeWizard Plug-In Battery using simple
# fixed-price margins derived from the ENTSO-e day-ahead price curve.
# It does NOT require percentile-based thresholds (Q1/Q3) or template
# sensors. Instead, it uses:
#
#   - low_threshold  = lowest_price + 0.03 EUR
#   - high_threshold = highest_price - (spread / 2.5)
#
# These thresholds approximate "cheap" and "expensive" hours and make
# the automation easier to set up for users who do not want to build
# the advanced percentile-based system.

alias: HomeWizard Battery Dynamic Control (Simple Version)
description: >
  Smart control of the HomeWizard Plug-In Battery based on ENTSO-e prices,
  PV export surplus and household load. Uses simple fixed margins rather
  than percentile-based thresholds to determine cheap and expensive hours.

mode: single

# ────────────────────────────────────────────────────────────────
# TRIGGERS
# ────────────────────────────────────────────────────────────────
triggers:
  # Trigger whenever the current market price changes
  - entity_id: sensor.entso_e_current_electricity_market_price
    trigger: state

  # And every 5 minutes to respond to SoC/load/export changes
  - minutes: /5
    trigger: time_pattern

conditions: []

actions:
  # ────────────────────────────────────────────────────────────────
  # VARIABLES
  # ────────────────────────────────────────────────────────────────
  - variables:
      # Price information
      current: "{{ states('sensor.entso_e_current_electricity_market_price') | float(0) }}"
      lowest: "{{ states('sensor.entso_e_lowest_energy_price') | float(0) }}"
      highest: "{{ states('sensor.entso_e_highest_energy_price') | float(0) }}"

      # Simple fixed-margins version
      low_margin: 0.03                                # 3 cents above the lowest price
      spread: "{{ (highest - lowest) | float(0) }}"   # Price spread of the day
      high_margin: "{{ (spread / 2.5) | float(0) }}"  # Upper margin based on spread

      # Thresholds equivalent to percentile-based logic
      low_threshold: "{{ lowest + low_margin }}"
      high_threshold: "{{ highest - high_margin }}"

      # Battery and power status
      soc: "{{ states('sensor.plug_in_battery_laadpercentage') | float(0) }}"
      export_power: "{{ states('sensor.p1_export_power') | float(0) }}"
      import_power: "{{ states('sensor.p1_import_power') | float(0) }}"

      # Profit calculation and thresholds
      tax: 0.14
      min_export_power: 0.05
      heavy_load_threshold: 2.0
      super_heavy_load_threshold: 9
      min_profit: 0.02
      rt_profit: "{{ ((highest + tax) * 0.75) - (lowest + tax) }}"

  # Ensure all required ENTSO-e sensors have valid states
  - condition: template
    value_template: >
      {{
        states('sensor.entso_e_current_electricity_market_price') not in ['unknown','unavailable']
        and states('sensor.entso_e_lowest_energy_price') not in ['unknown','unavailable']
        and states('sensor.entso_e_highest_energy_price') not in ['unknown','unavailable']
      }}

  # ────────────────────────────────────────────────────────────────
  # DECISION LOGIC
  # ────────────────────────────────────────────────────────────────
  - choose:

      # ────────────────────────────────────────────────────────────
      # 1. SUPER HEAVY LOAD — e.g. EV charging
      # Battery must stay completely out of the way → standby
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: "{{ import_power > super_heavy_load_threshold }}"
        sequence:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: standby }

      # ────────────────────────────────────────────────────────────
      # 2. PV EXPORT HACK — "charge-only" when solar surplus exists
      # Whenever there is real export and SoC < 98%, wake the battery
      # from standby and let it absorb the surplus → zero.
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: >
              {{ export_power > min_export_power and
                 soc < 98 }}
        sequence:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: zero }

      # ────────────────────────────────────────────────────────────
      # 3. ARBITRAGE NOT PROFITABLE ENOUGH
      # If potential spread profit is too low: avoid using the battery
      # for normal arbitrage. It still:
      #  - honours EV / super heavy load (rule 1)
      #  - honours PV surplus (rule 2)
      #  - may discharge in truly expensive hours.
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: "{{ rt_profit < min_profit }}"
        sequence:
          - choose:
              # 3.1 For all non-expensive hours → standby
              - conditions:
                  - condition: template
                    value_template: "{{ current <= high_threshold }}"
                sequence:
                  - action: select.select_option
                    target: { entity_id: select.p1_meter_batterijgroepmodus }
                    data: { option: standby }
            # 3.2 Expensive hours (current > high_threshold) → zero
            default:
              - action: select.select_option
                target: { entity_id: select.p1_meter_batterijgroepmodus }
                data: { option: zero }

      # ────────────────────────────────────────────────────────────
      # 4. EXPENSIVE HOURS — above high_threshold
      # When arbitrage *is* profitable:
      # Always discharge → zero
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: "{{ current > high_threshold }}"
        sequence:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: zero }

      # ────────────────────────────────────────────────────────────
      # 5. CHEAP HOURS + BATTERY (NEARLY) FULL
      # Do nothing → standby
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: "{{ current <= low_threshold and soc >= 98 }}"
        sequence:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: standby }

      # ────────────────────────────────────────────────────────────
      # 6. CHEAP HOURS + NO PV EXPORT + NOT FULL
      # Charge from the grid → to_full
      # (PV surplus cases are already handled by rule 2)
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: >
              {{ current <= low_threshold and soc < 98 and
                 export_power < min_export_power }}
        sequence:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: to_full }

      # ────────────────────────────────────────────────────────────
      # 7. MIDZONE (between low_threshold and high_threshold)
      # PV surplus cases are already handled in rule 2.
      # Remaining midzone behaviour:
      #  - no export → standby
      # ────────────────────────────────────────────────────────────
      - conditions:
          - condition: template
            value_template: >
              {{ current > low_threshold and
                 current <= high_threshold }}
        sequence:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: standby }

    # ────────────────────────────────────────────────────────────────
    # 8. FALLBACK — applies whenever no other logic branch matches.
    # Midzone defaults to standby, except when SoC < 10%.
    # A nearly-empty battery must not get stuck in standby.
    # ────────────────────────────────────────────────────────────────
    default:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ soc < 10 }}"
            sequence:
              - action: select.select_option
                target: { entity_id: select.p1_meter_batterijgroepmodus }
                data: { option: zero }
        default:
          - action: select.select_option
            target: { entity_id: select.p1_meter_batterijgroepmodus }
            data: { option: standby }
